Jenkinsfile: Disable build on macOS intel and arm
This is due to Beetle Supafaust not compiling on macOS versions since
Big Sur (version 11.0).

Errors are:

  mednafen/mthreading/MThreading_POSIX.cpp:585:5: error: use of undeclared identifier 'sem_timedwait'; did you mean 'Sem_TimedWait'?
   if(sem_timedwait(&sem->s, &abstime))
      ^~~~~~~~~~~~~
      Sem_TimedWait

  mednafen/mthreading/MThreading_POSIX.cpp:585:19: error: cannot initialize a parameter of type 'Mednafen::MThreading::Sem *' with an rvalue of type 'sem_t *' (aka 'int *')
   if(sem_timedwait(&sem->s, &abstime))
                    ^~~~~~~